[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "fastmcp>=2.12.3",
]
[tool.setuptools.packages.find]
include = ["main*"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
]
